" Name:         Raider
" Description:  A Vim colour scheme for archaeological escapades.
" Author:       Alex Vear <alex@vear.uk>
" Maintainer:   Alex Vear <alex@vear.uk>
" URL:          https://github.com/axvr/raider.vim
" License:      CC0 (Public domain)
" Last Updated: Mon 27 May 03:37:19 2024

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'raider'

let s:t_Co = has('gui_running') ? -1 : get(g:, 'raider_t_Co', get(g:, 't_Co', exists('&t_Co') ? +&t_Co : 0))

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#222222', '#cf4c4c', '#679d80', '#ecb55d', '#3465a4', '#75507b', '#29acc1', '#707070', '#2a2a2a', '#c61c29', '#2bb469', '#a79180', '#94baca', '#c061cb', '#34e2e2', '#c9c9c9']
endif
if has('nvim')
  let g:terminal_color_0 = '#222222'
  let g:terminal_color_1 = '#cf4c4c'
  let g:terminal_color_2 = '#679d80'
  let g:terminal_color_3 = '#ecb55d'
  let g:terminal_color_4 = '#3465a4'
  let g:terminal_color_5 = '#75507b'
  let g:terminal_color_6 = '#29acc1'
  let g:terminal_color_7 = '#707070'
  let g:terminal_color_8 = '#2a2a2a'
  let g:terminal_color_9 = '#c61c29'
  let g:terminal_color_10 = '#2bb469'
  let g:terminal_color_11 = '#a79180'
  let g:terminal_color_12 = '#94baca'
  let g:terminal_color_13 = '#c061cb'
  let g:terminal_color_14 = '#34e2e2'
  let g:terminal_color_15 = '#c9c9c9'
endif
hi Normal guifg=#c9c9c9 guibg=#222222 gui=NONE cterm=NONE
hi NonText guifg=#343434 guibg=bg gui=NONE cterm=NONE
hi Comment guifg=#707070 guibg=bg gui=NONE cterm=NONE
hi! link Conceal NonText
hi! link EndOfBuffer NonText
hi! link Delimiter Comment
hi Constant guifg=#88766f guibg=bg gui=NONE cterm=NONE
hi! link Character Constant
hi! link Number Constant
hi! link Float Number
hi! link Boolean Constant
hi String guifg=#94baca guibg=bg gui=NONE cterm=NONE
hi Identifier guifg=#96a8a1 guibg=bg gui=NONE cterm=NONE
hi! link Function Identifier
hi Statement guifg=#a79180 guibg=bg gui=NONE cterm=NONE
hi! link Conditional Statement
hi! link Repeat Statement
hi! link Label Statement
hi Exception guifg=#f0955f guibg=bg gui=NONE cterm=NONE
hi Keyword guifg=#858ca6 guibg=bg gui=NONE cterm=NONE
hi Operator guifg=#c9c9c9 guibg=bg gui=NONE cterm=NONE
hi PreProc guifg=#88766f guibg=bg gui=NONE cterm=NONE
hi! link Include PreProc
hi! link Macro PreProc
hi Define guifg=#a79180 guibg=bg gui=NONE cterm=NONE
hi! link PreCondit Define
hi Type guifg=#858ca6 guibg=bg gui=NONE cterm=NONE
hi! link StorageClass Type
hi! link Structure Type
hi! link Typedef Type
hi Special guifg=#88766f guibg=bg gui=NONE cterm=NONE
hi! link SpecialChar Special
hi! link Tag Special
hi! link SpecialComment Special
hi! link Debug Special
hi! link SpecialKey Special
hi ErrorMsg guifg=#cf4c4c guibg=bg gui=bold cterm=bold
hi! link Error ErrorMsg
hi WarningMsg guifg=#f0955f guibg=bg gui=bold cterm=bold
hi! link Warning WarningMsg
hi ModeMsg guifg=#94baca gui=NONE cterm=NONE
hi! link MoreMsg ModeMsg
hi! link Question ModeMsg
hi! link Ignore NonText
hi Todo guifg=#679d80 guibg=bg gui=bold cterm=bold
hi Underlined guifg=#94baca gui=underline cterm=underline
hi StatusLine guifg=#a79180 guibg=#343434 gui=NONE cterm=NONE
hi StatusLineNC guifg=#707070 guibg=#2a2a2a gui=NONE cterm=NONE
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link TabLine StatusLineNC
hi! link TabLineFill StatusLineNC
hi! link TabLineSel StatusLine
hi WildMenu guifg=#ecb55d guibg=#2a2a2a gui=NONE cterm=NONE
hi VertSplit guifg=#707070 gui=NONE cterm=NONE
hi! link WinSeparator VertSplit
hi! link NormalFloat Normal
hi! link FloatBorder WinSeparator
hi Title guifg=#a79180 gui=bold cterm=bold
hi LineNr guifg=#707070 gui=NONE cterm=NONE
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi Cursor guifg=#222222 guibg=#c9c9c9 gui=NONE cterm=NONE
hi CursorLine guibg=#2a2a2a gui=NONE cterm=NONE
hi CursorLineNr guifg=#ecb55d guibg=#2a2a2a gui=NONE cterm=NONE
hi! link CursorColumn CursorLine
hi ColorColumn guibg=#1a1a1a gui=NONE cterm=NONE
hi SignColumn guifg=#707070 guibg=bg gui=NONE cterm=NONE
hi Visual guibg=#343434 gui=NONE cterm=NONE
hi VisualNOS guibg=#343434 gui=NONE cterm=NONE
hi Pmenu guibg=#2a2a2a gui=NONE cterm=NONE
hi PmenuSbar guibg=#343434 gui=NONE cterm=NONE
hi PmenuSel guifg=#ecb55d guibg=#343434 gui=NONE cterm=NONE
hi PmenuThumb guibg=#707070 gui=NONE cterm=NONE
hi FoldColumn guifg=#2a2a2a gui=NONE cterm=NONE
hi Folded guifg=#707070 guibg=#1a1a1a gui=NONE cterm=NONE
hi IncSearch guifg=#222222 guibg=#ecb55d gui=NONE cterm=NONE
hi Search guifg=#222222 guibg=#94baca gui=NONE cterm=NONE
hi! link CurSearch IncSearch
hi Directory guifg=#94baca gui=NONE cterm=NONE
hi MatchParen guifg=#ecb55d guibg=#2a2a2a gui=bold cterm=bold
hi SpellBad guifg=#cf4c4c gui=underline cterm=underline
hi SpellCap guifg=#f0955f gui=underline cterm=underline
hi! link SpellLocal SpellCap
hi SpellRare guifg=#ecb55d gui=underline cterm=underline
hi QuickFixLine guifg=NONE guibg=#1a1a1a gui=NONE cterm=NONE
hi DiffAdd guifg=#679d80 guibg=#2a2a2a gui=NONE cterm=NONE
hi DiffChange guifg=fg guibg=#2a2a2a gui=NONE cterm=NONE
hi DiffDelete guifg=#cf4c4c guibg=#2a2a2a gui=NONE cterm=NONE
hi DiffText guifg=#ecb55d guibg=#2a2a2a gui=NONE cterm=NONE
hi! link diffAdded DiffAdd
hi! link diffRemoved DiffDelete
hi helpHyperTextJump guifg=#94baca guibg=bg gui=NONE cterm=NONE
hi! link htmlTag Delimiter
hi! link htmlEndTag htmlTag
hi! link gitcommitSummary Title

if s:t_Co >= 256
  hi Normal ctermfg=251 ctermbg=235 cterm=NONE
  hi NonText ctermfg=236 ctermbg=bg cterm=NONE
  hi Comment ctermfg=242 ctermbg=bg cterm=NONE
  hi! link Conceal NonText
  hi! link EndOfBuffer NonText
  hi! link Delimiter Comment
  hi Constant ctermfg=243 ctermbg=bg cterm=NONE
  hi! link Character Constant
  hi! link Number Constant
  hi! link Float Number
  hi! link Boolean Constant
  hi String ctermfg=109 ctermbg=bg cterm=NONE
  hi Identifier ctermfg=109 ctermbg=bg cterm=NONE
  hi! link Function Identifier
  hi Statement ctermfg=137 ctermbg=bg cterm=NONE
  hi! link Conditional Statement
  hi! link Repeat Statement
  hi! link Label Statement
  hi Exception ctermfg=173 ctermbg=bg cterm=NONE
  hi Keyword ctermfg=103 ctermbg=bg cterm=NONE
  hi Operator ctermfg=251 ctermbg=bg cterm=NONE
  hi PreProc ctermfg=243 ctermbg=bg cterm=NONE
  hi! link Include PreProc
  hi! link Macro PreProc
  hi Define ctermfg=137 ctermbg=bg cterm=NONE
  hi! link PreCondit Define
  hi Type ctermfg=103 ctermbg=bg cterm=NONE
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Typedef Type
  hi Special ctermfg=243 ctermbg=bg cterm=NONE
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link SpecialComment Special
  hi! link Debug Special
  hi! link SpecialKey Special
  hi ErrorMsg ctermfg=167 ctermbg=bg cterm=bold
  hi! link Error ErrorMsg
  hi WarningMsg ctermfg=173 ctermbg=bg cterm=bold
  hi! link Warning WarningMsg
  hi ModeMsg ctermfg=109 cterm=NONE
  hi! link MoreMsg ModeMsg
  hi! link Question ModeMsg
  hi! link Ignore NonText
  hi Todo ctermfg=72 ctermbg=bg cterm=bold
  hi Underlined ctermfg=109 cterm=underline
  hi StatusLine ctermfg=137 ctermbg=236 cterm=NONE
  hi StatusLineNC ctermfg=242 ctermbg=235 cterm=NONE
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi WildMenu ctermfg=179 ctermbg=235 cterm=NONE
  hi VertSplit ctermfg=242 cterm=NONE
  hi! link WinSeparator VertSplit
  hi! link NormalFloat Normal
  hi! link FloatBorder WinSeparator
  hi Title ctermfg=137 cterm=bold
  hi LineNr ctermfg=242 cterm=NONE
  hi! link LineNrAbove LineNr
  hi! link LineNrBelow LineNr
  hi Cursor ctermfg=235 ctermbg=251 cterm=NONE
  hi CursorLine ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=179 ctermbg=235 cterm=NONE
  hi! link CursorColumn CursorLine
  hi ColorColumn ctermbg=234 cterm=NONE
  hi SignColumn ctermfg=242 ctermbg=bg cterm=NONE
  hi Visual ctermbg=236 cterm=NONE
  hi VisualNOS ctermbg=236 cterm=NONE
  hi Pmenu ctermbg=235 cterm=NONE
  hi PmenuSbar ctermbg=236 cterm=NONE
  hi PmenuSel ctermfg=179 ctermbg=236 cterm=NONE
  hi PmenuThumb ctermbg=242 cterm=NONE
  hi FoldColumn ctermfg=235 cterm=NONE
  hi Folded ctermfg=242 ctermbg=234 cterm=NONE
  hi IncSearch ctermfg=235 ctermbg=179 cterm=NONE
  hi Search ctermfg=235 ctermbg=109 cterm=NONE
  hi! link CurSearch IncSearch
  hi Directory ctermfg=109 cterm=NONE
  hi MatchParen ctermfg=179 ctermbg=235 cterm=bold
  hi SpellBad ctermfg=167 cterm=underline
  hi SpellCap ctermfg=173 cterm=underline
  hi! link SpellLocal SpellCap
  hi SpellRare ctermfg=179 cterm=underline
  hi QuickFixLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi DiffAdd ctermfg=72 ctermbg=235 cterm=NONE
  hi DiffChange ctermfg=fg ctermbg=235 cterm=NONE
  hi DiffDelete ctermfg=167 ctermbg=235 cterm=NONE
  hi DiffText ctermfg=179 ctermbg=235 cterm=NONE
  hi! link diffAdded DiffAdd
  hi! link diffRemoved DiffDelete
  hi helpHyperTextJump ctermfg=109 ctermbg=bg cterm=NONE
  hi! link htmlTag Delimiter
  hi! link htmlEndTag htmlTag
  hi! link gitcommitSummary Title
  unlet s:t_Co
  finish
endif

" Background: dark
" Color: void      #1a1a1a ~  ; Darkest background.
" Color: shadows   #222222 ~  ; Background.
" Color: shade     #2a2a2a ~  ; Lighter background.
" Color: hidden    #343434 ~  ; Invisible.
" Color: gun_metal #707070 ~  ; Faded forground.
" Color: snow      #c9c9c9 ~  ; Foreground.
" Color: top       #94baca ~  ; Teal.
" Color: shorts    #a79180 ~  ; Light yellowish-brown.
" Color: boots     #88766f ~  ; Light redish-brown.
" Color: snow_jacket #f0955f ~  ; Orange.
" Color: leaves    #679d80 ~  ; Pale blueish-green.
" Color: moss      #96a8a1 ~  ; Pale greenish-teal.
" Color: slate     #858ca6 ~  ; Purplish-blue.
" Color: blood     #cf4c4c ~  ; Red.
" Color: gold      #ecb55d ~  ; Yellow.
" Color: term_b_blue    #3465a4 ~
" Color: term_b_magenta #75507b ~
" Color: term_b_cyan    #29acc1 ~
" Color: term_red       #c61c29 ~
" Color: term_green     #2bb469 ~
" Color: term_magenta   #c061cb ~
" Color: term_cyan      #34e2e2 ~
" Term Colors: shadows   blood    leaves     gold    term_b_blue term_b_magenta term_b_cyan gun_metal  ; Bold
" Term Colors: shade     term_red term_green shorts  top         term_magenta   term_cyan   snow       ; Normal
" vim: et ts=8 sw=2 sts=2
